on:
  push:
    branches:
      - master
  pull_request:
    types: [ assigned, opened, synchronize, reopened, labeled ]
name: ci
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22, 24, 26]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - run: node --version
      - run: npm install --engine-strict
      - run: npm test
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - run: npm install
      - run: npm test
