on:
   push:
     branches:
       - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: get-pkg-repo
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://external-dot-oss-automation.appspot.com/'
        if: ${{ steps.release.outputs.release_created }}
      - run: npm install
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
